language: java
jdk: openjdk7
branches: 
only:
- master
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
notifications:
  email:
    on_success: never
    on_failure: always
after_success:
- openssl aes-256-cbc -K $encrypted_37c44ba70a11_key -iv $encrypted_37c44ba70a11_iv -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
- openssl aes-256-cbc -K $encrypted_37c44ba70a11_key -iv $encrypted_37c44ba70a11_iv -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
- "$GPG_DIR/publish.sh"